import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  //Used to deliberately throw hydration error
  const isServer = typeof window === "undefined";

  return (
    <div className={styles.container}>
      <Head>
        <title>React Hydration Error - Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          {`Hydration Error Caused by this text --> ${
            isServer ? "SERVER" : "CLIENT"
          }`}
        </h1>
        <span className={styles.description}>
          Open devtools and you will see our custom React Hydration Error with
          text starting with ReactHydrationError
        </span>
        <div className={styles.socialContainer}>
          <div>
            This demo was a part of my medium article, you can check it out on{" "}
            <a href="https://medium.com/@suncommander/how-to-catch-and-log-react-hydration-errors-3f507ca83d5f">
              Medium
            </a>
            .
          </div>
          <div>
            You can also check the source code for this on{" "}
            <a href="https://github.com/amitsingh-007/react-hydration-error">
              GitHub
            </a>
            .
          </div>
        </div>
      </main>
    </div>
  );
}
